version: '3.7'

services:
    postgres:
        image: postgres:14-alpine
        container_name: postgres
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        command: postgres -c 'max_connections=500'
        volumes:
            - pai_postgres_volume:/var/lib/postgresql/data
        ports:
            - "5499:5432"
        networks:
            - private

    redis:
        image: redis:6-alpine
        container_name: redis
        command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
        env_file:
            - .env
        volumes:
            - pai_redis_volume:/data
        ports:
            - "6399:6379"
        networks:
            - private
    api:
        build:
            context: .
        restart: always
        container_name: ${PROJECT_NAME}
        ports:
            - 3000:${SERVER_PORT}
        env_file:
            - .env
        depends_on:
            - redis
            - postgres
        networks:
            - private
networks:
    private:
        driver: bridge
    

volumes:
    pai_postgres_volume:
        driver: local
    pai_redis_volume:
        driver: local