name: Deploy [v3.0]

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Environment
        uses: mkyai/env-builder@v2.0.0-0 
        with:
          secrets: ${{ toJson(secrets) }}
          variables: ${{ toJson(vars) }}

