name: Deploy [v3.0]

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Environment
        uses: mkyai/env-builder@v1.0.1
        with:
          secrets: ${{ toJson(secrets) }}
          variables: ${{ toJson(vars) }}

      # - name: Get Artifacts
      #   run: |
      #     curl -o artifacts ${{ secrets.ARTIFACTS_URL }}

      - name: Deploy
        uses: mkyai/zip-deploy@v1.0.7
